apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kube-httpcache.fullname" . }}
  labels:
    {{- include "kube-httpcache.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "kube-httpcache.selectorLabels" . | nindent 6 }}
