{{- if not .Values.cache.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-httpcache.fullname" . }}
  labels:
    {{- include "kube-httpcache.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.cache.secret | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}
