apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-httpcache.fullname" . }}
  labels:
    {{- include "kube-httpcache.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target }}
      protocol: TCP
    - name: "signaller"
      port: 8090
      targetPort: 8090
    {{- if .Values.exporter.enabled }}
    - name: metrics
      port: 9131
      targetPort: 9131
    {{- end }}
  selector:
    {{- include "kube-httpcache.selectorLabels" . | nindent 4 }}
