name: Release Dev Tags

on:
  push:
    tags:
      - '*-alpha*'
      - '*-beta*'
      - '*-rc*'

jobs:
  build:
    name: Build and release dev image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.24"
      - name: Docker login
        run: docker login -u "${{ secrets.QUAY_IO_USER }}" -p "${{ secrets.QUAY_IO_TOKEN }}" quay.io
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: "0.181.1"
          args: release --rm-dist -f build/ci/.goreleaser-dev.yml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_USER_TOKEN }}
