name: Test

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  verify_helm:
    name: Verify Helm chart
    runs-on: ubuntu-latest
    strategy:
      matrix:
        helm: [ '3.1.2' ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Helm
        run: |
          wget https://get.helm.sh/helm-v${{ matrix.helm }}-linux-amd64.tar.gz -O /tmp/helm.tar.gz
          tar xzf /tmp/helm.tar.gz -C /tmp --strip-components=1
          chmod +x /tmp/helm
      - name: Test template rendering
        run: /tmp/helm template ./chart/.

      - name: Lint chart
        run: /tmp/helm lint ./chart/

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.24"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: "0.181.1"
          args: release -f build/ci/.goreleaser.yml --snapshot --skip-publish --rm-dist
